### PR TITLE
update craft recipes

### PR DESCRIPTION
**Pull request by Napiophelios**
update craft recipes that use xpanes nodes as craft items

### CODE REVIEW

**Comment by AcidNinjaFWHR** [comment]
👍  for merging this

**Comment by sofar** [comment]
:+1:

**Comment by kilbith** [comment]
@sofar Dude, once again you forgot to set the aliases in upstream (the first time being with the doors). Just a warning.

**Comment by sofar** [comment]
Yeah, I focused on converting map nodes, completely forgot about ItemStack items.

**Comment by sofar** [comment]
But, we can't alias them. Both `xpanes:bar` and `xpanes:bar_flat` are nodes that are in use in `minetest_game`. Aliasing them would break everything.

**Comment by tchncs** [comment]
I am happy to see your name in the xdecor repo again, @kilbith 🚀

**Pull request merged**
