### PR TITLE
Add CC BY 4.0 Int'l replacements for non-free textures

### PR DESCRIPTION
**Pull request by MCLx86**
The speaker, radio, hanging candle, and weather cock textures by gigomaf are non-free (i.e. CC BY-**NC** 3.0 licensed), [many users on the forums were rightfully upset about this](https://forum.minetest.net/viewtopic.php?f=11&t=12534&start=308), so I decided to make free replacements, this would also help promote the mod, as you would then be able to remove the "Non-free media" label on ContentDB that may discourage potential players.

I am the author of all these textures and I release them under the terms of the Creative Commons Attribution 4.0 International license, available here: https://creativecommons.org/licenses/by/4.0/legalcode

### CODE REVIEW

**Comment by kilbith** [comment]
Can you show me some in-game before/after screenshots please?

**Comment by MCLx86** [comment]
> Can you show me some in-game before/after screenshots please?
screenshot_20220827_093454
screenshot_20220827_093032

**Comment by kilbith** [comment]
Ok, I appreciate your contribution (I really do). But I consider them inferior to the current ones, even with better licensing.

I'm sorry, I hope you don't take it personally.

**Comment by MCLx86** [comment]
Do you consider all of them to be inferior? I do think that the rooster and candle ones are kind of bad, but the radio and speaker look very similar to the originals. Could you please point out what in particular do you not like about them? I would be happy to fix whatever you don't like.

**Comment by kilbith** [comment]
The radio and speaker look very similar indeed, I would take only these ones.

**Comment by MCLx86** [comment]
I reverted the weathercock (rooster) and hanging candle textures.

**Comment by MCLx86** [comment]
Someone on the forums made this CC0/WTFPL wind vane texture, what do you think of it?

image

**Comment by kilbith** [comment]
Yes, I like this one.

**Comment by MCLx86** [comment]
Somebody also made this one, it's CC0 and it's very similar to the original. If you want, I can add it to the fork and update the pull request.
image

**Comment by Wuzzy2** [comment]
I like MCLx86's rooster.

**Comment by MCLx86** [comment]
Added the weather cock. Ready to merge.

**Comment by MCLx86** [comment]
@kilbith

**Comment by Wuzzy2** [comment]
I've created X-Decor-libre, a libre fork of X-Decor. It includes the previous submssions, as well as the missing two files `xdecor_enchanting.ogg` and `xdecor_candle_hanging.png`.

You can use this mod as a drop-in replacement for `xdecor`.

https://codeberg.org/Wuzzy/xdecor-libre

I think I will keep maintaining this repo as long the original `xdecor` remains non-free. PRs for improved graphics are welcome!

**Pull request closed without merging**
